<script lang="ts">
  import Sheet from './Sheet.svelte';

  interface Props {
    onClose: () => void;
  }
  let { onClose }: Props = $props();
</script>

<!--
  Renders the bundled `licenses.html` (generated by `pnpm gen:licenses`) in an
  in-app iframe. We must NOT use `openUrl`/`target="_blank"` here: in the Tauri
  release the asset lives under the internal `tauri://localhost` origin, which the
  external system browser cannot resolve, so the link silently does nothing. An
  iframe stays inside the webview (same origin) and works on desktop, Android and
  in the dev browser alike. CSP is `null`, so the same-origin frame is allowed.
-->
<Sheet open={true} title="Drittanbieter-Lizenzen" {onClose}>
  <iframe class="licenses-frame" src="/licenses.html" title="Drittanbieter-Lizenzen"></iframe>
</Sheet>

<style>
  .licenses-frame {
    width: 100%;
    height: 70vh;
    border: 0;
    border-radius: 8px;
    background: #fff;
  }
</style>
